import tkinter as tkk

# desabilitar botoes
def disable_buttons(file_menu, samp_menu, demonstrativos_menu, sparta_menu):
    file_menu.entryconfig('Anexar', state='active')
    samp_menu.entryconfig('Baixar SAMP (ANEEL)', state='active')
    samp_menu.entryconfig('Baixar SAMP (Dados Abertos)', state='active')
    samp_menu.entryconfig('Adicionar SAMP na pasta MERCADO', state='active')
    samp_menu.entryconfig('Copiar dados da SAMP para RA0', state='active')
    demonstrativos_menu.entryconfig('00', state='active')
    demonstrativos_menu.entryconfig('01', state='active')
    demonstrativos_menu.entryconfig('02', state='active')
    demonstrativos_menu.entryconfig('03', state='active')
    demonstrativos_menu.entryconfig('04', state='active')
    demonstrativos_menu.entryconfig('05', state='active')
    demonstrativos_menu.entryconfig('06', state='active')
    demonstrativos_menu.entryconfig('07', state='active')
    demonstrativos_menu.entryconfig('08', state='active')
    demonstrativos_menu.entryconfig('09', state='active')
    demonstrativos_menu.entryconfig('10', state='active')
    sparta_menu.entryconfig('Atualizar', state='active')

def enable_buttons(file_menu, samp_menu, demonstrativos_menu, sparta_menu):
    file_menu.entryconfig('Anexar', state='disabled')
    samp_menu.entryconfig('Baixar SAMP (ANEEL)', state='disabled')
    samp_menu.entryconfig('Baixar SAMP (Dados Abertos)', state='disabled')
    samp_menu.entryconfig('Adicionar SAMP na pasta MERCADO', state='disabled')
    samp_menu.entryconfig('Copiar dados da SAMP para RA0', state='disabled')
    demonstrativos_menu.entryconfig('00', state='disabled')
    demonstrativos_menu.entryconfig('01', state='disabled')
    demonstrativos_menu.entryconfig('02', state='disabled')
    demonstrativos_menu.entryconfig('03', state='disabled')
    demonstrativos_menu.entryconfig('04', state='disabled')
    demonstrativos_menu.entryconfig('05', state='disabled')
    demonstrativos_menu.entryconfig('06', state='disabled')
    demonstrativos_menu.entryconfig('07', state='disabled')
    demonstrativos_menu.entryconfig('08', state='disabled')
    demonstrativos_menu.entryconfig('09', state='disabled')
    demonstrativos_menu.entryconfig('10', state='disabled')
    sparta_menu.entryconfig('Atualizar', state='disabled')